plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/generated'
        }
    }
}

dependencies {
    // Dependencies
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
    compileOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    compileOnly "dev.emi:emi-xplat-mojmap:${emi_version}"

    // Terrablender
    compileOnly "maven.modrinth:kkmrDlKT:6e8GCrLb"

    // Abnormals
    compileOnly "maven.modrinth:blueprint:${blueprint_version}"
    compileOnly "maven.modrinth:autumnity:${autumnity_version}"
    compileOnly "maven.modrinth:environmental:${environmental_version}"
    // compileOnly "maven.modrinth:caverns-and-chasms:${caverns_and_chasms_version}"

    // JNE
    compileOnly "maven.modrinth:jadens-nether-expansion:${jne_version}"

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.6'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources tasks.named("processResources")
}